[package]
name = "greqlint_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_json = "*"
schemars = "*"
greqlint_schema = { path = "../greqlint_schema" }
regex = "1.10.2"
